# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 22:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=128)),
                ('origin', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=140)),
                ('contentType', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('categories', models.CharField(max_length=128)),
                ('count', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('nextComments', models.CharField(max_length=128, verbose_name='next')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('uuid', models.CharField(max_length=36, verbose_name='id')),
                ('visibility', models.CharField(max_length=10)),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('visibleTo', models.ManyToManyField(related_name='visibleTo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
