# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='PUBLIC', max_length=10),
        ),
    ]
