# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20170309_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanSee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibleTo', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='visibleTo',
        ),
        migrations.AddField(
            model_name='cansee',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Post'),
        ),
    ]
