# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 17:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20170303_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibleTo',
            field=models.ManyToManyField(blank=True, related_name='visibleTo', to=settings.AUTH_USER_MODEL),
        ),
    ]
