# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20170309_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='dash.Author'),
        ),
    ]
