# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_auto_20170303_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='nextComments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='size',
        ),
    ]
