# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_auto_20170308_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='uuid',
            new_name='id',
        ),
    ]
