# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('remoteToLocalUsername', models.TextField()),
                ('remoteToLocalPassword', models.TextField()),
                ('localToRemoteUserName', models.TextField()),
                ('localToRemotePassword', models.TextField()),
            ],
        ),
    ]
