# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20170313_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotenode',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
