# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_auto_20170325_0355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localcredentials',
            options={'verbose_name_plural': 'LocalCredentials'},
        ),
        migrations.AlterModelOptions(
            name='remotecredentials',
            options={'verbose_name_plural': 'RemoteCredentials'},
        ),
    ]
