# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_auto_20170325_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotecredentials',
            name='host',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='remotecredentials',
            name='username',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='remotecredentials',
            unique_together=set([('host', 'username')]),
        ),
    ]
