# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20170309_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published']},
        ),
    ]
