# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20170313_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorfriend',
            name='author',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='requestee',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='requester',
        ),
        migrations.DeleteModel(
            name='AuthorFriend',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
