# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20170323_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.URLField(),
        ),
    ]
