# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_auto_20170310_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='source',
        ),
    ]
