# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_follow_is_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='friend',
            new_name='follower',
        ),
    ]
