# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_remove_post_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, default=None, null=True)),
                ('useauth', models.NullBooleanField(default=None)),
                ('username', models.TextField(blank=True, default=None, null=True)),
                ('password', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='displayName',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='firstName',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_author_friends_+', to='dash.Author'),
        ),
        migrations.AddField(
            model_name='author',
            name='lastName',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
