# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_auto_20170312_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(blank=True, default='https://cmput404t06.herokuapp.com/dash/', max_length=500, null=True),
        ),
    ]
