# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_auto_20170326_0720'),
        ('dash', '0008_auto_20170326_0334'),
    ]

    operations = [
    ]
