# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_merge_20170326_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='friend',
        ),
    ]
