# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_auto_20170326_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='is_friend',
        ),
        migrations.AddField(
            model_name='follow',
            name='requesterDisplayName',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='requesterDisplayName',
            field=models.CharField(default='', max_length=256),
        ),
    ]
