# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0011_auto_20170312_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
