# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0011_auto_20170326_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='requesterDisplayName',
            new_name='friendDisplayName',
        ),
    ]
