# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0012_auto_20170312_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(blank=True, default='http://127.0.0.1:8000/dash', max_length=500, null=True),
        ),
    ]
